# Generated by Django 2.0.4 on 2018-05-25 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='dftgroup',
            name='name',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='first_name',
            field=models.CharField(default='First Name', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_name',
            field=models.CharField(default='Last Name', max_length=100),
        ),
        migrations.AddField(
            model_name='division',
            name='dft_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.DfTGroup'),
        ),
        migrations.AddField(
            model_name='employee',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Division'),
        ),
    ]
