version: "3.7"

services:
  redis:
    image: redis:7.0-alpine
  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=dbasik
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db_data:/var/lib/postgresql/data
  web:
    build:
      context: .
    volumes:
      - .:/app
    restart: "unless-stopped"
    environment:
      - DJANGO_SUPERUSER_USERNAME=lemon
      - DJANGO_SUPERUSER_EMAIL=lemon@lemon.com
      - DJANGO_SUPERUSER_PASSWORD=lemonlemon
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKED=redis://redis:6379/0
    command: >
      bash -c "python manage.py migrate --noinput && \
      python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    depends_on:
      - db
      - redis
  celery_worker: # we just use the Django container for this
    # build:
    #   context: .
    image: python:3-slim
    restart: unless-stopped
    command: celery -A config worker -l INFO
    volumes:
      - .:/app # creates a volume which maps the . directory in our project to /app in the container - allowing us to sync our changes
      - ./data/web:/vol/web
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKED=redis://redis:6379/0
    depends_on:
      - redis
      - db
      - web
#      - cache
volumes:
  db_data:
