version: "3.7"

services:
  redis:
    image: redis:7.0-alpine
  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=dbasik
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db_data:/var/lib/postgresql/data
  web:
    build:
      context: .
    volumes:
      - .:/app
    restart: "unless-stopped"
    environment:
      - DJANGO_SUPERUSER_USERNAME=lemon
      - DJANGO_SUPERUSER_EMAIL=lemon@lemon.com
      - DJANGO_SUPERUSER_PASSWORD=lemonlemon
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKED=redis://redis:6379/0
    command: >
      bash -c "celery -A dbasik.config worker --loglevel=INFO && \
               python manage.py migrate --noinput && \
               python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
      - "6379:6379"
    stdin_open: true
    tty: true
    depends_on:
      - db
      - redis
volumes:
  db_data:
