# Generated by Django 2.1.3 on 2018-11-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnitem',
            name='value_date',
            field=models.DateField(blank=True),
        ),
    ]
