# Generated by Django 2.1.3 on 2018-11-27 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datamap', '0007_auto_20181116_1552'),
        ('returns', '0005_auto_20181127_0546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='return',
            name='datamapline',
        ),
        migrations.AddField(
            model_name='return',
            name='datamap',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_datamaps', to='datamap.Datamap'),
        ),
    ]
