# Generated by Django 2.1.3 on 2018-12-09 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0010_auto_20181209_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnitem',
            name='value_str',
            field=models.CharField(blank=True, default='', max_length=1024, null=True),
        ),
    ]
