# Generated by Django 2.1.3 on 2018-11-30 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0008_auto_20181122_1653"),
        ("returns", "0007_auto_20181127_0554"),
    ]

    operations = [
        migrations.AddField(
            model_name="returnitem",
            name="value_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="return",
            unique_together={("project", "financial_quarter")},
        ),
    ]
