# Generated by Django 2.1.3 on 2018-12-09 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("returns", "0009_auto_20181130_1837"),
    ]

    operations = [
        migrations.AlterField(
            model_name="returnitem",
            name="parent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="return_returnitems",
                to="returns.Return",
            ),
        ),
        migrations.AlterField(
            model_name="returnitem",
            name="value_str",
            field=models.CharField(blank=True, default="", max_length=512, null=True),
        ),
    ]
