# Generated by Django 2.1.3 on 2018-12-09 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("returns", "0012_auto_20181209_2058"),
    ]

    operations = [
        migrations.AlterField(
            model_name="returnitem",
            name="value_str",
            field=models.CharField(blank=True, default="", max_length=4096, null=True),
        ),
    ]
