# Generated by Django 4.0.3 on 2022-03-31 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0015_alter_returnitem_value_int'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnitem',
            name='value_phone',
            field=models.CharField(blank=True, default='', max_length=45, null=True),
        ),
    ]
