# Generated by Django 2.0.4 on 2018-05-28 14:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datamap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, default=uuid.uuid1)),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Tier')),
            ],
        ),
        migrations.CreateModel(
            name='DatamapLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('sheet', models.CharField(max_length=50)),
                ('cell_ref', models.CharField(max_length=10)),
                ('datamap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamap.Datamap')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='datamap',
            unique_together={('slug', 'tier')},
        ),
    ]
