# Generated by Django 2.0.4 on 2018-05-20 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datamap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=False)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='DatamapLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('sheet', models.CharField(max_length=50)),
                ('cell_ref', models.CharField(max_length=10)),
                ('datamap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamap.Datamap')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioFamily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='datamap',
            name='portfolio_family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datamaps', to='datamap.PortfolioFamily'),
        ),
        migrations.AlterUniqueTogether(
            name='datamap',
            unique_together={('slug', 'portfolio_family')},
        ),
    ]
