# Generated by Django 2.0.5 on 2018-05-30 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamap',
            name='active',
            field=models.BooleanField(default=False, unique=True),
        ),
    ]
