# Generated by Django 2.0.5 on 2018-05-30 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_tier_slug'),
        ('datamap', '0002_auto_20180530_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamap',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='datamap',
            unique_together={('slug', 'tier', 'active')},
        ),
    ]
