# Generated by Django 2.0.5 on 2018-05-30 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_tier_slug'),
        ('datamap', '0003_auto_20180530_1530'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='datamap',
            unique_together={('tier', 'active')},
        ),
    ]
