# Generated by Django 2.0.5 on 2018-06-01 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamap', '0004_auto_20180530_1532'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='datamapline',
            unique_together={('sheet', 'cell_ref')},
        ),
    ]
