# Generated by Django 2.0.5 on 2018-06-01 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamap', '0005_auto_20180601_0555'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='datamapline',
            unique_together={('datamap', 'sheet', 'cell_ref')},
        ),
    ]
