# Generated by Django 2.0.5 on 2018-06-01 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamap', '0006_auto_20180601_1854'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='datamap',
            unique_together=set(),
        ),
    ]
