# Generated by Django 2.0.5 on 2018-06-02 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_projectstage_slug'),
        ('datamap', '0007_auto_20180601_1856'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='datamap',
            unique_together={('name', 'tier')},
        ),
    ]
