# Generated by Django 2.0.4 on 2018-05-25 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_auto_20180525_0550'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyDeliveryPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField(blank=True)),
                ('planned_end_date', models.DateField(blank=True)),
                ('baseline_wlc', models.FloatField(blank=True)),
                ('agency_delivery_partner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='register.AgencyDeliveryPartner')),
                ('dependency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='register.Project')),
                ('dft_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.DfTGroup')),
                ('director', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='director_projects', to='users.Employee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectPhase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StrategicAlignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='project',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.ProjectPhase'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.ProjectType'),
        ),
        migrations.AddField(
            model_name='project',
            name='sro',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='sro_projects', to='users.Employee'),
        ),
        migrations.AddField(
            model_name='project',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.ProjectStage'),
        ),
        migrations.AddField(
            model_name='project',
            name='tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Tier'),
        ),
    ]
