# Generated by Django 2.0.4 on 2018-05-29 19:32

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttype',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['name']),
        ),
        migrations.AlterField(
            model_name='project',
            name='dependencies',
            field=models.ManyToManyField(blank=True, to='register.Project'),
        ),
        migrations.AlterField(
            model_name='projecttype',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
