# Generated by Django 2.0.4 on 2018-05-26 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180525_0550'),
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Constraint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('background', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('background', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mandate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_position', models.TextField(blank=True)),
                ('critIcal_success_factor', models.TextField(blank=True)),
                ('deliverable1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mandate_deliverable1', to='register.Deliverable')),
                ('deliverable2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mandate_deliverable2', to='register.Deliverable')),
                ('deliverable3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mandate_deliverable3', to='register.Deliverable')),
                ('deliverable4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mandate_deliverable4', to='register.Deliverable')),
                ('deliverable5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mandate_deliverable5', to='register.Deliverable')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PortfolioInitialisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_methodology', models.TextField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('planned_end_date', models.DateField(blank=True, null=True)),
                ('strategic_outline_business_case_approval', models.DateField(blank=True, null=True)),
                ('outline_business_case_approval', models.DateField(blank=True, null=True)),
                ('full_business_case_approval', models.DateField(blank=True, null=True)),
                ('start_of_construction_build', models.DateField(blank=True, null=True)),
                ('start_of_operations', models.DateField(blank=True, null=True)),
                ('agency_delivery_partner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='register.AgencyDeliveryPartner')),
                ('classification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.Classification')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.DfTGroup')),
                ('initial_project_assurance_milestone1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_init_assurance_milestone1', to='register.Milestone')),
                ('initial_project_assurance_milestone2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_init_assurance_milestone2', to='register.Milestone')),
                ('initial_project_assurance_milestone3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_init_assurance_milestone3', to='register.Milestone')),
                ('initial_project_assurance_milestone4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_init_assurance_milestone4', to='register.Milestone')),
                ('initial_project_assurance_milestone5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_init_assurance_milestone5', to='register.Milestone')),
                ('milestone1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_init_milestone1', to='register.Milestone')),
                ('milestone2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_init_milestone2', to='register.Milestone')),
                ('milestone3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_init_milestone3', to='register.Milestone')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RAGColour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RiskRPA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('background', models.TextField(blank=True)),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.RAGColour')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StrategicOutcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('background', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='project',
            name='mandate_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='agency_delivery_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='register.AgencyDeliveryPartner'),
        ),
        migrations.AlterField(
            model_name='project',
            name='baseline_wlc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='dft_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.DfTGroup'),
        ),
        migrations.AlterField(
            model_name='project',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_director', to='users.Employee'),
        ),
        migrations.AlterField(
            model_name='project',
            name='phase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.ProjectPhase'),
        ),
        migrations.AlterField(
            model_name='project',
            name='planned_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.ProjectType'),
        ),
        migrations.AlterField(
            model_name='project',
            name='sro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_sro', to='users.Employee'),
        ),
        migrations.AlterField(
            model_name='project',
            name='stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.ProjectStage'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolioinitialisation',
            name='risk_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.RiskRPA'),
        ),
        migrations.AddField(
            model_name='mandate',
            name='external_organisation_affected1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mandate_external_org_affected1', to='register.Organisation'),
        ),
        migrations.AddField(
            model_name='mandate',
            name='external_organisation_affected2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mandate_external_org_affected2', to='register.Organisation'),
        ),
        migrations.AddField(
            model_name='mandate',
            name='external_organisation_affected3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mandate_external_org_affected3', to='register.Organisation'),
        ),
        migrations.AddField(
            model_name='mandate',
            name='external_organisation_affected4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mandate_external_org_affected4', to='register.Organisation'),
        ),
        migrations.AddField(
            model_name='mandate',
            name='external_organisation_affected5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mandate_external_org_affected5', to='register.Organisation'),
        ),
        migrations.AddField(
            model_name='mandate',
            name='internal_organisation_affected1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mandate_internal_org_affected1', to='register.Organisation'),
        ),
        migrations.AddField(
            model_name='mandate',
            name='internal_organisation_affected2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mandate_internal_org_affected2', to='register.Organisation'),
        ),
        migrations.AddField(
            model_name='mandate',
            name='internal_organisation_affected3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mandate_internal_org_affected3', to='register.Organisation'),
        ),
        migrations.AddField(
            model_name='mandate',
            name='internal_organisation_affected4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mandate_internal_org_affected4', to='register.Organisation'),
        ),
        migrations.AddField(
            model_name='mandate',
            name='internal_organisation_affected5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mandate_internal_org_affected5', to='register.Organisation'),
        ),
        migrations.AddField(
            model_name='mandate',
            name='key_risk1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mandate_key_risk1', to='register.RiskRPA'),
        ),
        migrations.AddField(
            model_name='mandate',
            name='key_risk2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mandate_key_risk2', to='register.RiskRPA'),
        ),
        migrations.AddField(
            model_name='mandate',
            name='key_risk3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mandate_key_risk3', to='register.RiskRPA'),
        ),
        migrations.AddField(
            model_name='mandate',
            name='key_risk4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mandate_key_risk4', to='register.RiskRPA'),
        ),
        migrations.AddField(
            model_name='mandate',
            name='key_risk5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mandate_key_risk5', to='register.RiskRPA'),
        ),
        migrations.AddField(
            model_name='mandate',
            name='known_constraint1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mandate_constraint1', to='register.Constraint'),
        ),
        migrations.AddField(
            model_name='mandate',
            name='known_constraint2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mandate_constraint2', to='register.Constraint'),
        ),
        migrations.AddField(
            model_name='mandate',
            name='known_constraint3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mandate_constraint3', to='register.Constraint'),
        ),
        migrations.AddField(
            model_name='mandate',
            name='known_constraint4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mandate_constraint4', to='register.Constraint'),
        ),
        migrations.AddField(
            model_name='mandate',
            name='known_constraint5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mandate_constraint5', to='register.Constraint'),
        ),
        migrations.AddField(
            model_name='mandate',
            name='objective1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mandate_objective_1', to='register.Objective'),
        ),
        migrations.AddField(
            model_name='mandate',
            name='objective2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mandate_objective_2', to='register.Objective'),
        ),
        migrations.AddField(
            model_name='mandate',
            name='objective3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mandate_objective_3', to='register.Objective'),
        ),
        migrations.AddField(
            model_name='mandate',
            name='objective4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mandate_objective_4', to='register.Objective'),
        ),
        migrations.AddField(
            model_name='mandate',
            name='objective5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mandate_objective_5', to='register.Objective'),
        ),
        migrations.AddField(
            model_name='mandate',
            name='strategic_outcome1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_strat_outcome1', to='register.StrategicOutcome'),
        ),
        migrations.AddField(
            model_name='mandate',
            name='strategic_outcome2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_strat_outcome2', to='register.StrategicOutcome'),
        ),
        migrations.AddField(
            model_name='mandate',
            name='strategic_outcome3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_strat_outcome3', to='register.StrategicOutcome'),
        ),
        migrations.AddField(
            model_name='mandate',
            name='strategic_outcome4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_strat_outcome4', to='register.StrategicOutcome'),
        ),
        migrations.AddField(
            model_name='mandate',
            name='strategic_outcome5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_strat_outcome5', to='register.StrategicOutcome'),
        ),
        migrations.AddField(
            model_name='project',
            name='mandate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.Mandate'),
        ),
        migrations.AddField(
            model_name='project',
            name='portfolio_initialisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.PortfolioInitialisation'),
        ),
    ]
