# Generated by Django 2.0.4 on 2018-05-30 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20180529_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttype',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
