# Generated by Django 2.0.5 on 2018-05-30 13:13

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_projecttype_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tier',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['name']),
        ),
    ]
