# Generated by Django 2.0.5 on 2018-06-01 05:55

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_tier_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstage',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['name']),
        ),
    ]
