# Generated by Django 2.0.5 on 2018-06-02 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_projectstage_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tier',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
