# Generated by Django 2.1.3 on 2018-11-22 16:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_auto_20181119_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialquarter',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='financialquarter',
            name='label',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='financialquarter',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
