# Generated by Django 2.1.3 on 2018-11-22 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_auto_20181122_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialquarter',
            name='start_date',
            field=models.DateField(blank=True, null=True, unique=True),
        ),
    ]
