# Generated by Django 2.1.3 on 2018-11-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0004_financialquarter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financialquarter",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="financialquarter",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
