# Generated by Django 4.0.5 on 2022-06-24 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_dftdivision_id_alter_dftgroup_id_and_more'),
        ('register', '0010_remove_project_baseline_wlc_and_more'),
    ]

