# Generated by Django 2.1.3 on 2018-11-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="template",
            name="source_file",
            field=models.FileField(upload_to="uploaded_templates/"),
        ),
    ]
