# Generated by Django 2.1.3 on 2019-02-23 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0002_auto_20181116_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateDataLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet', models.CharField(max_length=255)),
                ('cellref', models.CharField(max_length=10)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='templates.Template')),
            ],
        ),
    ]
