# Generated by Django 2.1.3 on 2019-02-24 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0003_templatedataline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='source_file',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='templatedataline',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='templates.Template'),
        ),
    ]
