# Generated by Django 2.0.5 on 2018-06-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datamapline',
            name='data_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('INTEGER', 'Integer'), ('FLOAT', 'Float'), ('DATE', 'Date')], default='TEXT', max_length=10),
        ),
        migrations.AddField(
            model_name='datamapline',
            name='max_length',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='datamapline',
            name='required',
            field=models.BooleanField(default=True),
        ),
    ]
