# Generated by Django 4.0.2 on 2022-02-28 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamap', '0008_auto_20181209_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamap',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='datamapline',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='datamapline',
            name='key',
            field=models.CharField(max_length=255),
        ),
    ]
