# Generated by Django 4.0.8 on 2022-10-28 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0012_alter_project_dft_group'),
        ('datamap', '0010_alter_datamapline_data_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamap',
            name='tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='register.tier'),
        ),
    ]
